// 参考 Verge Rev 示例 Script 配置
//
// Clash Verge Rev (Version ≥ 17.2) & Mihomo-Party (Version ≥ 1.5.10)
//
// 最后更新时间: 2025-05-01 22:37

// 规则集通用配置
const ruleProviderCommon = {
};

// 策略组通用配置
const groupBaseOption = {
  "interval": 300,
  "url": "http://www.apple.com/library/test/success.html",
  "max-failed-times": 3,
};

// 程序入口
function main(config) {
  const proxyCount = config?.proxies?.length ?? 0;
  const proxyProviderCount =
    typeof config?.["proxy-providers"] === "object" ? Object.keys(config["proxy-providers"]).length : 0;
  if (proxyCount === 0 && proxyProviderCount === 0) {
    throw new Error("配置文件中未找到任何代理");
  }
  // 覆盖通用配置
  config["mixed-port"] = "7890";
  config["tcp-concurrent"] = true;
  config["allow-lan"] = true;
  config["ipv6"] = true;
  config["log-level"] = "info";
  config["unified-delay"] = false;
  config["find-process-mode"] = "strict";
  config["global-client-fingerprint"] = "safari";

  // 覆盖 dns 配置
  config["dns"] = {
    "enable": true,
    "cache-algorithm": "lru",
    "listen": "0.0.0.0:1053",
    "ipv6": true,
    "enhanced-mode": "fake-ip",
    "fake-ip-range": "198.18.0.1/16",
    "fake-ip-filter": ["*", "+.lan", "+.local", "+.direct", "+.msftconnecttest.com", "rule-set:Game", "rule-set:fakeip-filter", "+.msftncsi.com"],
    "default-nameserver": ["223.5.5.5", "119.29.29.29"],
    "nameserver": ["https://dns.alidns.com/dns-query", "https://doh.pub/dns-query"],
    "proxy-server-nameserver": ["https://dns.alidns.com/dns-query", "https://doh.pub/dns-query"]    
  };
  
  // 覆盖 tun 配置
  config["tun"] = {
    "enable": true,
    "stack": "mixed",
    "dns-hijack": ["any:53"],
    "auto-route": true,
    "auto-detect-interface": true
  };
     
  // 覆盖 geodata 配置
  config["geodata-mode"] = true;
  config["geox-url"] = {
    "geoip": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat",
    "geosite": "https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat",
    "mmdb": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb",
    "asn": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"
  }; 
  
  
  
  // 覆盖 sniffer 配置
  config["sniffer"] = {
    "enable": true,
    "parse-pure-ip": true,
    "sniff": {
      "TLS": {
        "ports": ["443", "1-99999"]
      },
      "HTTP": {
        "ports": ["80", "1-99999"],
        "override-destination": true
      },
      "QUIC": {
        "ports": ["443", "1-99999"]
      }
    }
  };
      
  // 覆盖策略组
  config["proxy-groups"] = [
    {
      ...groupBaseOption,
      "name": "Final",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png"
    },
    {
      ...groupBaseOption,
      "name": "Game",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png"
    },
    {
      ...groupBaseOption,
      "name": "YouTube",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png"
    },
    {
      ...groupBaseOption,
      "name": "TelegramSG",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Telegram.png"
    },

    {
      ...groupBaseOption,
      "name": "TelegramUS",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Telegram.png"
    },

    {
      ...groupBaseOption,
      "name": "TelegramEU",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Orz-3/mini@master/Color/Telegram.png"
    },

    {
      ...groupBaseOption,
      "name": "GoogleVoice",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Semporia/Hand-Painted-icon@master/Google_Suite/Voice.png"
    },

    {
      ...groupBaseOption,
      "name": "Google",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png"
    },

    {
      ...groupBaseOption,
      "name": "BiliBili",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili.png"
    },
    {
      ...groupBaseOption,
      "name": "OpenAI",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/openai.png"
    },
    {
      ...groupBaseOption,
      "name": "Emby",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Emby.png"
    },
    {
      ...groupBaseOption,
      "name": "Instagram",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Instagram.png"
    },
    {
      ...groupBaseOption,
      "name": "Pixiv",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Pornhub.png"
    },
    {
      ...groupBaseOption,
      "name": "TikTok",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png"
    },
    {
      ...groupBaseOption,
      "name": "Twitter",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset",
      "proxies": ["香港节点(url-test)", "台湾节点(url-test)", "新加坡节点(url-test)", "日本节点(url-test)", "美国节点(url-test)", "欧洲节点(url-test)", "香港节点(select)", "台湾节点(select)", "新加坡节点(select)", "日本节点(select)", "美国节点(select)", "欧洲节点(select)", "Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)", "AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)", "NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)", "Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)", "AIFUN节点", "Nexitally节点", "NEXAIR节点", "Kuromi节点", "ChinaAirport节点"],
     "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png"
    },
    {
      ...groupBaseOption,
      "name": "Nexitally节点",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "proxies": ["Nexitally香港节点(url-test)", "Nexitally台湾节点(url-test)", "Nexitally新加坡节点(url-test)", "Nexitally日本节点(url-test)", "Nexitally美国节点(url-test)", "Nexitally欧洲节点(url-test)", "Nexitally香港节点(select)", "Nexitally台湾节点(select)", "Nexitally新加坡节点(select)", "Nexitally日本节点(select)", "Nexitally美国节点(select)", "Nexitally欧洲节点(select)"],
    },
    {
      ...groupBaseOption, 
      "name": "AIFUN节点",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/Nexitally(1).png",
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "proxies": ["AIFUN香港节点(url-test)", "AIFUN台湾节点(url-test)", "AIFUN新加坡节点(url-test)", "AIFUN日本节点(url-test)", "AIFUN美国节点(url-test)", "AIFUN欧洲节点(url-test)", "AIFUN香港节点(select)", "AIFUN台湾节点(select)", "AIFUN新加坡节点(select)", "AIFUN日本节点(select)", "AIFUN美国节点(select)", "AIFUN欧洲节点(select)"]
    },
    {
      ...groupBaseOption,
      "name": "NEXAIR节点",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/Nexitally(1).png",
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "proxies": ["NEXAIR香港节点(url-test)", "NEXAIR台湾节点(url-test)", "NEXAIR新加坡节点(url-test)", "NEXAIR日本节点(url-test)", "NEXAIR美国节点(url-test)", "NEXAIR欧洲节点(url-test)", "NEXAIR香港节点(select)", "NEXAIR台湾节点(select)", "NEXAIR新加坡节点(select)", "NEXAIR日本节点(select)", "NEXAIR美国节点(select)", "NEXAIR欧洲节点(select)"]
    },
    {
      ...groupBaseOption,
      "name": "Kuromi节点",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/Kuromi.png",
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "proxies": ["Kuromi香港节点(url-test)", "Kuromi台湾节点(url-test)", "Kuromi新加坡节点(url-test)", "Kuromi日本节点(url-test)", "Kuromi美国节点(url-test)", "Kuromi欧洲节点(url-test)", "Kuromi香港节点(select)", "Kuromi台湾节点(select)", "Kuromi新加坡节点(select)", "Kuromi日本节点(select)", "Kuromi美国节点(select)", "Kuromi欧洲节点(select)"]
    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport节点",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TAG.png",
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "proxies": ["ChinaAirport香港节点(url-test)", "ChinaAirport台湾节点(url-test)", "ChinaAirport新加坡节点(url-test)", "ChinaAirport日本节点(url-test)", "ChinaAirport美国节点(url-test)", "ChinaAirport欧洲节点(url-test)", "ChinaAirport香港节点(select)", "ChinaAirport台湾节点(select)", "ChinaAirport新加坡节点(select)", "ChinaAirport日本节点(select)", "ChinaAirport美国节点(select)", "ChinaAirport欧洲节点(select)"]
    },
    {
      ...groupBaseOption,
      "name": "BANAD",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true,
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Reject.png",
      "proxies": ["REJECT", "REJECT-DROP", "PASS"]
    },
    {
      ...groupBaseOption,
      "name": "香港节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",
      "proxies": ["Nexitally香港节点(url-test)", "AIFUN香港节点(url-test)", "NEXAIR香港节点(url-test)", "Kuromi香港节点(url-test)"]
    },
    {
      ...groupBaseOption,
      "name": "台湾节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",    
      "proxies": ["Nexitally台湾节点(url-test)", "AIFUN台湾节点(url-test)", "NEXAIR台湾节点(url-test)", "Kuromi台湾节点(url-test)"]
    },
    {
      ...groupBaseOption,
      "name": "新加坡节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",
      "proxies": ["Nexitally新加坡节点(url-test)", "AIFUN新加坡节点(url-test)", "NEXAIR新加坡节点(url-test)", "Kuromi新加坡节点(url-test)"]
    },
    {
      ...groupBaseOption,
      "name": "日本节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",
      "proxies": ["Nexitally日本节点(url-test)", "AIFUN日本节点(url-test)", "NEXAIR日本节点(url-test)", "Kuromi日本节点(url-test)"]
    },
    {
      ...groupBaseOption,
      "name": "美国节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",
      "proxies": ["Nexitally美国节点(url-test)", "AIFUN美国节点(url-test)", "NEXAIR美国节点(url-test)", "Kuromi美国节点(url-test)"]
    },
    {
      ...groupBaseOption,    
      "name": "欧洲节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png",
      "proxies": ["Nexitally欧洲节点(url-test)", "AIFUN欧洲节点(url-test)", "NEXAIR欧洲节点(url-test)", "Kuromi欧洲节点(url-test)"]
    },
    {
      ...groupBaseOption,
      "name": "Nexitally香港节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)🇭🇰|香港|Hong|HK",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",
    },
    {
      ...groupBaseOption,
      "name": "Nexitally台湾节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)TW|🇹🇼|台湾|TaiWan|🇨🇳",
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",
    },
    {
      ...groupBaseOption,
      "name": "Nexitally日本节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)日本|JP|Japan|🇯🇵",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",
    },
    {
      ...groupBaseOption,
      "name": "Nexitally新加坡节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)SG|新加坡|🇸🇬|Singapore",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",
    },
    {
      ...groupBaseOption,
      "name": "Nexitally美国节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)美国|States|American|USA|Seattle|San Jose|Los Angeles|🇺🇸",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",
    },
    {
      ...groupBaseOption,
      "name": "Nexitally欧洲节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)德国|法国|荷兰|意大利|西班牙|土耳其|挪威|瑞士|瑞典|爱尔兰|芬兰|丹麦|波兰|匈牙利|英国|UK|比利时|卢森堡|希腊|葡萄牙|俄罗斯|爱尔兰|斯洛伐克|保加利亚|塞尔维亚|克罗地亚|奥地利|摩纳哥|立陶宛|拉脱维亚|罗马尼亚|捷克|乌克兰|Germany|France|Netherlands|Italy|Spain|Turkey|Norway|Switzerland|Sweden|Ireland|Finland|Denmark|Poland|Hungary|UnitedKingdom|UK|Belgium|Luxembourg|Greece|Portugal|Russia|Ireland|Slovakia|Bulgaria|Serbia|Croatia|Austria|Monaco|Lithuania|Latvia|Romania|Czech|Republic|Ukraine|🇩🇪|🇫🇷|🇳🇱|🇮🇹|🇪🇸|🇹🇷|🇳🇴|🇨🇭|🇸🇪|🇮🇪|🇫🇮|🇩🇰|🇵🇱|🇭🇺|🇧🇪|🇱🇺|🇬🇷|🇵🇹|🇦🇹|🇱🇹|🇱🇻|🇷🇴|🇨🇿|🌍|🇺🇦|🇬🇧|🇷🇺|🇮🇪|🇸🇰|🇧🇬|🇷🇸|🇭🇷|🇲🇨",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png",
    },
    {
      ...groupBaseOption,    
      "name": "AIFUN香港节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)🇭🇰|香港|Hong|HK",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",
    },
    {
      ...groupBaseOption,
      "name": "AIFUN台湾节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)TW|🇹🇼|台湾|TaiWan|🇨🇳",
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",

    },
    {
      ...groupBaseOption,
      "name": "AIFUN日本节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)日本|JP|Japan|🇯🇵",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",


    },
    {
      ...groupBaseOption,
      "name": "AIFUN新加坡节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)SG|新加坡|🇸🇬|Singapore",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",


    },
    {
      ...groupBaseOption,
      "name": "AIFUN美国节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)美国|States|American|USA|Seattle|San Jose|Los Angeles|🇺🇸",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",

    },
    {
      ...groupBaseOption,
      "name": "AIFUN欧洲节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)德国|法国|荷兰|意大利|西班牙|土耳其|挪威|瑞士|瑞典|爱尔兰|芬兰|丹麦|波兰|匈牙利|英国|UK|比利时|卢森堡|希腊|葡萄牙|俄罗斯|爱尔兰|斯洛伐克|保加利亚|塞尔维亚|克罗地亚|奥地利|摩纳哥|立陶宛|拉脱维亚|罗马尼亚|捷克|乌克兰|Germany|France|Netherlands|Italy|Spain|Turkey|Norway|Switzerland|Sweden|Ireland|Finland|Denmark|Poland|Hungary|UnitedKingdom|UK|Belgium|Luxembourg|Greece|Portugal|Russia|Ireland|Slovakia|Bulgaria|Serbia|Croatia|Austria|Monaco|Lithuania|Latvia|Romania|Czech|Republic|Ukraine|🇩🇪|🇫🇷|🇳🇱|🇮🇹|🇪🇸|🇹🇷|🇳🇴|🇨🇭|🇸🇪|🇮🇪|🇫🇮|🇩🇰|🇵🇱|🇭🇺|🇧🇪|🇱🇺|🇬🇷|🇵🇹|🇦🇹|🇱🇹|🇱🇻|🇷🇴|🇨🇿|🌍|🇺🇦|🇬🇧|🇷🇺|🇮🇪|🇸🇰|🇧🇬|🇷🇸|🇭🇷|🇲🇨",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png",

    },
    {
      ...groupBaseOption,
      "name": "NEXAIR香港节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)🇭🇰|香港|Hong|HK",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",


    },
    {
      ...groupBaseOption,
      "name": "NEXAIR台湾节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)TW|🇹🇼|台湾|TaiWan|🇨🇳",
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",

    },
    {
      ...groupBaseOption,
      "name": "NEXAIR日本节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)日本|JP|Japan|🇯🇵",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",


    },
    {
      ...groupBaseOption,
      "name": "NEXAIR新加坡节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)SG|新加坡|🇸🇬|Singapore",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",


    },
    {
      ...groupBaseOption,
      "name": "NEXAIR美国节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)美国|States|American|USA|Seattle|San Jose|Los Angeles|🇺🇸",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",

    },
    {
      ...groupBaseOption,
      "name": "NEXAIR欧洲节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)德国|法国|荷兰|意大利|西班牙|土耳其|挪威|瑞士|瑞典|爱尔兰|芬兰|丹麦|波兰|匈牙利|英国|UK|比利时|卢森堡|希腊|葡萄牙|俄罗斯|爱尔兰|斯洛伐克|保加利亚|塞尔维亚|克罗地亚|奥地利|摩纳哥|立陶宛|拉脱维亚|罗马尼亚|捷克|乌克兰|Germany|France|Netherlands|Italy|Spain|Turkey|Norway|Switzerland|Sweden|Ireland|Finland|Denmark|Poland|Hungary|UnitedKingdom|UK|Belgium|Luxembourg|Greece|Portugal|Russia|Ireland|Slovakia|Bulgaria|Serbia|Croatia|Austria|Monaco|Lithuania|Latvia|Romania|Czech|Republic|Ukraine|🇩🇪|🇫🇷|🇳🇱|🇮🇹|🇪🇸|🇹🇷|🇳🇴|🇨🇭|🇸🇪|🇮🇪|🇫🇮|🇩🇰|🇵🇱|🇭🇺|🇧🇪|🇱🇺|🇬🇷|🇵🇹|🇦🇹|🇱🇹|🇱🇻|🇷🇴|🇨🇿|🌍|🇺🇦|🇬🇧|🇷🇺|🇮🇪|🇸🇰|🇧🇬|🇷🇸|🇭🇷|🇲🇨",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png",
  
    },
    {
      ...groupBaseOption,
      "name": "Kuromi香港节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)🇭🇰|香港|Hong|HK",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",


    },
    {
      ...groupBaseOption,
      "name": "Kuromi台湾节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)TW|🇹🇼|台湾|TaiWan|🇨🇳",
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",

    },
    {
      ...groupBaseOption,
      "name": "Kuromi日本节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)日本|JP|Japan|🇯🇵",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",


    },
    {
      ...groupBaseOption,
      "name": "Kuromi新加坡节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)SG|新加坡|🇸🇬|Singapore",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",

    },
    {
      ...groupBaseOption,
      "name": "Kuromi美国节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)美国|States|American|USA|Seattle|San Jose|Los Angeles|🇺🇸",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",

    },
    {
      ...groupBaseOption,
      "name": "Kuromi欧洲节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)德国|法国|荷兰|意大利|西班牙|土耳其|挪威|瑞士|瑞典|爱尔兰|芬兰|丹麦|波兰|匈牙利|英国|UK|比利时|卢森堡|希腊|葡萄牙|俄罗斯|爱尔兰|斯洛伐克|保加利亚|塞尔维亚|克罗地亚|奥地利|摩纳哥|立陶宛|拉脱维亚|罗马尼亚|捷克|乌克兰|Germany|France|Netherlands|Italy|Spain|Turkey|Norway|Switzerland|Sweden|Ireland|Finland|Denmark|Poland|Hungary|UnitedKingdom|UK|Belgium|Luxembourg|Greece|Portugal|Russia|Ireland|Slovakia|Bulgaria|Serbia|Croatia|Austria|Monaco|Lithuania|Latvia|Romania|Czech|Republic|Ukraine|🇩🇪|🇫🇷|🇳🇱|🇮🇹|🇪🇸|🇹🇷|🇳🇴|🇨🇭|🇸🇪|🇮🇪|🇫🇮|🇩🇰|🇵🇱|🇭🇺|🇧🇪|🇱🇺|🇬🇷|🇵🇹|🇦🇹|🇱🇹|🇱🇻|🇷🇴|🇨🇿|🌍|🇺🇦|🇬🇧|🇷🇺|🇮🇪|🇸🇰|🇧🇬|🇷🇸|🇭🇷|🇲🇨",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png",

  
    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport香港节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)🇭🇰|香港|Hong|HK",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",


    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport台湾节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)TW|🇹🇼|台湾|TaiWan|🇨🇳",
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",

    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport日本节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)日本|JP|Japan|🇯🇵",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",


    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport新加坡节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)SG|新加坡|🇸🇬|Singapore",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",


    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport美国节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)美国|States|American|USA|Seattle|San Jose|Los Angeles|🇺🇸",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",


    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport欧洲节点(url-test)",
      "type": "url-test",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)德国|法国|荷兰|意大利|西班牙|土耳其|挪威|瑞士|瑞典|爱尔兰|芬兰|丹麦|波兰|匈牙利|英国|UK|比利时|卢森堡|希腊|葡萄牙|俄罗斯|爱尔兰|斯洛伐克|保加利亚|塞尔维亚|克罗地亚|奥地利|摩纳哥|立陶宛|拉脱维亚|罗马尼亚|捷克|乌克兰|Germany|France|Netherlands|Italy|Spain|Turkey|Norway|Switzerland|Sweden|Ireland|Finland|Denmark|Poland|Hungary|UnitedKingdom|UK|Belgium|Luxembourg|Greece|Portugal|Russia|Ireland|Slovakia|Bulgaria|Serbia|Croatia|Austria|Monaco|Lithuania|Latvia|Romania|Czech|Republic|Ukraine|🇩🇪|🇫🇷|🇳🇱|🇮🇹|🇪🇸|🇹🇷|🇳🇴|🇨🇭|🇸🇪|🇮🇪|🇫🇮|🇩🇰|🇵🇱|🇭🇺|🇧🇪|🇱🇺|🇬🇷|🇵🇹|🇦🇹|🇱🇹|🇱🇻|🇷🇴|🇨🇿|🌍|🇺🇦|🇬🇧|🇷🇺|🇮🇪|🇸🇰|🇧🇬|🇷🇸|🇭🇷|🇲🇨",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png"
    },
    {
      ...groupBaseOption,
      "name": "香港节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",
    proxies: ["Nexitally香港节点(select)", "AIFUN香港节点(select)", "NEXAIR香港节点(select)", "Kuromi香港节点(select)", "ChinaAirport香港节点(select)"]

    },
    {
      ...groupBaseOption,
      "name": "台湾节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",    
    proxies: ["Nexitally台湾节点(select)", "AIFUN台湾节点(select)", "NEXAIR台湾节点(select)", "Kuromi台湾节点(select)", "ChinaAirport台湾节点(select)"]

    },
    {
      ...groupBaseOption,
      "name": "新加坡节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",
    proxies: ["Nexitally新加坡节点(select)", "AIFUN新加坡节点(select)", "NEXAIR新加坡节点(select)", "Kuromi新加坡节点(select)", "ChinaAirport新加坡节点(select)"]
    
    },
    {
      ...groupBaseOption,
      "name": "日本节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",
    proxies: ["Nexitally日本节点(select)", "NEXAIR日本节点(select)", "AIFUN日本节点(select)", "Kuromi日本节点(select)", "ChinaAirport日本节点(select)"]

    },
    {
      ...groupBaseOption,
      "name": "美国节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",
    proxies: ["Nexitally美国节点(select)", "AIFUN美国节点(select)", "NEXAIR美国节点(select)", "Kuromi美国节点(select)", "ChinaAirport美国节点(select)"]

    },
    {
      ...groupBaseOption,
      "name": "欧洲节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png",
    proxies: ["Nexitally欧洲节点(select)", "AIFUN欧洲节点(select)", "NEXAIR欧洲节点(select)", "Kuromi欧洲节点(select)", "ChinaAirport欧洲节点(select)"]

    },
    {
      ...groupBaseOption,
      "name": "Nexitally香港节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)🇭🇰|香港|Hong|HK",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",

      
    },
    {
      ...groupBaseOption,
      "name": "Nexitally台湾节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)TW|🇹🇼|台湾|TaiWan|🇨🇳",
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",
    
    },
    {
      ...groupBaseOption,
      "name": "Nexitally新加坡节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)SG|新加坡|🇸🇬|Singapore",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",

    },
    {
      ...groupBaseOption,
      "name": "Nexitally日本节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)日本|JP|Japan|🇯🇵",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",

    },
    {
      ...groupBaseOption,
      "name": "Nexitally美国节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)美国|States|American|USA|Seattle|San Jose|Los Angeles|🇺🇸",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",


    },
    {
      ...groupBaseOption,
      "name": "Nexitally欧洲节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|AIFUN|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)德国|法国|荷兰|意大利|西班牙|土耳其|挪威|瑞士|瑞典|爱尔兰|芬兰|丹麦|波兰|匈牙利|英国|UK|比利时|卢森堡|希腊|葡萄牙|俄罗斯|爱尔兰|斯洛伐克|保加利亚|塞尔维亚|克罗地亚|奥地利|摩纳哥|立陶宛|拉脱维亚|罗马尼亚|捷克|乌克兰|Germany|France|Netherlands|Italy|Spain|Turkey|Norway|Switzerland|Sweden|Ireland|Finland|Denmark|Poland|Hungary|UnitedKingdom|UK|Belgium|Luxembourg|Greece|Portugal|Russia|Ireland|Slovakia|Bulgaria|Serbia|Croatia|Austria|Monaco|Lithuania|Latvia|Romania|Czech|Republic|Ukraine|🇩🇪|🇫🇷|🇳🇱|🇮🇹|🇪🇸|🇹🇷|🇳🇴|🇨🇭|🇸🇪|🇮🇪|🇫🇮|🇩🇰|🇵🇱|🇭🇺|🇧🇪|🇱🇺|🇬🇷|🇵🇹|🇦🇹|🇱🇹|🇱🇻|🇷🇴|🇨🇿|🌍|🇺🇦|🇬🇧|🇷🇺|🇮🇪|🇸🇰|🇧🇬|🇷🇸|🇭🇷|🇲🇨",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png",
    
    },
    {
      ...groupBaseOption,
      "name": "AIFUN香港节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)🇭🇰|香港|Hong|HK",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",

      
    },
    {
      ...groupBaseOption,
      "name": "AIFUN台湾节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)TW|🇹🇼|台湾|TaiWan|🇨🇳",
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",
    
    },
    {
      ...groupBaseOption,
      "name": "AIFUN新加坡节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)SG|新加坡|🇸🇬|Singapore",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",

    },
    {
      ...groupBaseOption,
      "name": "AIFUN日本节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)日本|JP|Japan|🇯🇵",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",

    },
    {
      ...groupBaseOption,
      "name": "AIFUN美国节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)美国|States|American|USA|Seattle|San Jose|Los Angeles|🇺🇸",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",


    },
    {
      ...groupBaseOption,
      "name": "AIFUN欧洲节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|NEXAIR|Kuromi|ChinaAirport",
      "filter": "(?i)德国|法国|荷兰|意大利|西班牙|土耳其|挪威|瑞士|瑞典|爱尔兰|芬兰|丹麦|波兰|匈牙利|英国|UK|比利时|卢森堡|希腊|葡萄牙|俄罗斯|爱尔兰|斯洛伐克|保加利亚|塞尔维亚|克罗地亚|奥地利|摩纳哥|立陶宛|拉脱维亚|罗马尼亚|捷克|乌克兰|Germany|France|Netherlands|Italy|Spain|Turkey|Norway|Switzerland|Sweden|Ireland|Finland|Denmark|Poland|Hungary|UnitedKingdom|UK|Belgium|Luxembourg|Greece|Portugal|Russia|Ireland|Slovakia|Bulgaria|Serbia|Croatia|Austria|Monaco|Lithuania|Latvia|Romania|Czech|Republic|Ukraine|🇩🇪|🇫🇷|🇳🇱|🇮🇹|🇪🇸|🇹🇷|🇳🇴|🇨🇭|🇸🇪|🇮🇪|🇫🇮|🇩🇰|🇵🇱|🇭🇺|🇧🇪|🇱🇺|🇬🇷|🇵🇹|🇦🇹|🇱🇹|🇱🇻|🇷🇴|🇨🇿|🌍|🇺🇦|🇬🇧|🇷🇺|🇮🇪|🇸🇰|🇧🇬|🇷🇸|🇭🇷|🇲🇨",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png",

    },
    {
      ...groupBaseOption,
      "name": "NEXAIR香港节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)🇭🇰|香港|Hong|HK",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",

      
    },
    {
      ...groupBaseOption,
      "name": "NEXAIR台湾节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)TW|🇹🇼|台湾|TaiWan|🇨🇳",
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",
    
    },
    {
      ...groupBaseOption,
      "name": "NEXAIR新加坡节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)SG|新加坡|🇸🇬|Singapore",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",

    },
    {
      ...groupBaseOption,
      "name": "NEXAIR日本节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)日本|JP|Japan|🇯🇵",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",

    },
    {
      ...groupBaseOption,
      "name": "NEXAIR美国节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)美国|States|American|USA|Seattle|San Jose|Los Angeles|🇺🇸",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",


    },
    {
      ...groupBaseOption,
      "name": "NEXAIR欧洲节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|Kuromi|AIFUN|ChinaAirport",
      "filter": "(?i)德国|法国|荷兰|意大利|西班牙|土耳其|挪威|瑞士|瑞典|爱尔兰|芬兰|丹麦|波兰|匈牙利|英国|UK|比利时|卢森堡|希腊|葡萄牙|俄罗斯|爱尔兰|斯洛伐克|保加利亚|塞尔维亚|克罗地亚|奥地利|摩纳哥|立陶宛|拉脱维亚|罗马尼亚|捷克|乌克兰|Germany|France|Netherlands|Italy|Spain|Turkey|Norway|Switzerland|Sweden|Ireland|Finland|Denmark|Poland|Hungary|UnitedKingdom|UK|Belgium|Luxembourg|Greece|Portugal|Russia|Ireland|Slovakia|Bulgaria|Serbia|Croatia|Austria|Monaco|Lithuania|Latvia|Romania|Czech|Republic|Ukraine|🇩🇪|🇫🇷|🇳🇱|🇮🇹|🇪🇸|🇹🇷|🇳🇴|🇨🇭|🇸🇪|🇮🇪|🇫🇮|🇩🇰|🇵🇱|🇭🇺|🇧🇪|🇱🇺|🇬🇷|🇵🇹|🇦🇹|🇱🇹|🇱🇻|🇷🇴|🇨🇿|🌍|🇺🇦|🇬🇧|🇷🇺|🇮🇪|🇸🇰|🇧🇬|🇷🇸|🇭🇷|🇲🇨",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png",
          
    },
    {
      ...groupBaseOption,
      "name": "Kuromi香港节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)🇭🇰|香港|Hong|HK",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",


    },
    {
      ...groupBaseOption,
      "name": "Kuromi台湾节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)TW|🇹🇼|台湾|TaiWan|🇨🇳",  
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",
    
    },
    {
      ...groupBaseOption,
      "name": "Kuromi新加坡节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)SG|新加坡|🇸🇬|Singapore",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",
    
    },
    {
      ...groupBaseOption,
      "name": "Kuromi日本节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)日本|JP|Japan|🇯🇵",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",
    },
    {
      ...groupBaseOption,
      "name": "Kuromi美国节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)美国|States|American|USA|Seattle|San Jose|Los Angeles|🇺🇸",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",

    },
    {
      ...groupBaseOption,
      "name": "Kuromi欧洲节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Nexitally|AIFUN|NEXAIR|ChinaAirport",
      "filter": "(?i)德国|法国|荷兰|意大利|西班牙|土耳其|挪威|瑞士|瑞典|爱尔兰|芬兰|丹麦|波兰|匈牙利|英国|UK|比利时|卢森堡|希腊|葡萄牙|俄罗斯|爱尔兰|斯洛伐克|保加利亚|塞尔维亚|克罗地亚|奥地利|摩纳哥|立陶宛|拉脱维亚|罗马尼亚|捷克|乌克兰|Germany|France|Netherlands|Italy|Spain|Turkey|Norway|Switzerland|Sweden|Ireland|Finland|Denmark|Poland|Hungary|UnitedKingdom|UK|Belgium|Luxembourg|Greece|Portugal|Russia|Ireland|Slovakia|Bulgaria|Serbia|Croatia|Austria|Monaco|Lithuania|Latvia|Romania|Czech|Republic|Ukraine|🇩🇪|🇫🇷|🇳🇱|🇮🇹|🇪🇸|🇹🇷|🇳🇴|🇨🇭|🇸🇪|🇮🇪|🇫🇮|🇩🇰|🇵🇱|🇭🇺|🇧🇪|🇱🇺|🇬🇷|🇵🇹|🇦🇹|🇱🇹|🇱🇻|🇷🇴|🇨🇿|🌍|🇺🇦|🇬🇧|🇷🇺|🇮🇪|🇸🇰|🇧🇬|🇷🇸|🇭🇷|🇲🇨",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png",


    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport香港节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)🇭🇰|香港|Hong|HK",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",
    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport台湾节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)TW|🇹🇼|台湾|TaiWan|🇨🇳",
      "icon": "https://raw.githubusercontent.com/lige47/QuanX-icon-rule/refs/heads/main/icon/taiwan(2).png",

    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport新加坡节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)SG|新加坡|🇸🇬|Singapore",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",

    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport日本节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)日本|JP|Japan|🇯🇵",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",

    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport美国节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)美国|States|American|USA|Seattle|San Jose|Los Angeles|🇺🇸",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",

    },
    {
      ...groupBaseOption,
      "name": "ChinaAirport欧洲节点(select)",
      "type": "select",
      "udp": true,
      "tfo": true,
      "mptcp": true,
      "udp-over-tcp": true,
      "udp-over-tcp-version": "2",
      "include-all": true, 
      "exclude-filter": "Days Left|国内|国际|工单|重置|套餐|回国|官网|Premium|GB|Expire Date|Traffic Reset|Kuromi|AIFUN|Nexitally|NEXAIR",
      "filter": "(?i)德国|法国|荷兰|意大利|西班牙|土耳其|挪威|瑞士|瑞典|爱尔兰|芬兰|丹麦|波兰|匈牙利|英国|UK|比利时|卢森堡|希腊|葡萄牙|俄罗斯|爱尔兰|斯洛伐克|保加利亚|塞尔维亚|克罗地亚|奥地利|摩纳哥|立陶宛|拉脱维亚|罗马尼亚|捷克|乌克兰|Germany|France|Netherlands|Italy|Spain|Turkey|Norway|Switzerland|Sweden|Ireland|Finland|Denmark|Poland|Hungary|UnitedKingdom|UK|Belgium|Luxembourg|Greece|Portugal|Russia|Ireland|Slovakia|Bulgaria|Serbia|Croatia|Austria|Monaco|Lithuania|Latvia|Romania|Czech|Republic|Ukraine|🇩🇪|🇫🇷|🇳🇱|🇮🇹|🇪🇸|🇹🇷|🇳🇴|🇨🇭|🇸🇪|🇮🇪|🇫🇮|🇩🇰|🇵🇱|🇭🇺|🇧🇪|🇱🇺|🇬🇷|🇵🇹|🇦🇹|🇱🇹|🇱🇻|🇷🇴|🇨🇿|🌍|🇺🇦|🇬🇧|🇷🇺|🇮🇪|🇸🇰|🇧🇬|🇷🇸|🇭🇷|🇲🇨",
      "icon": "https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/European_Union.png"
    }
  ];
            
  // 覆盖规则集
  config["rule-providers"] = {
    "Game": {
      ...ruleProviderCommon,
      "behavior": "classical",
      "url": "https://raw.githubusercontent.com/ccc52266/CC/main/README.md",
      "path": "./rules/Game",
      "type": "http",
      "format": "text",
      "interval": 86400
    },
    "TelegramSG": {
      ...ruleProviderCommon,
      "behavior": "classical",
      "url": "https://raw.githubusercontent.com/ccc52266/embyh/main/clash",
      "path": "./rules/TelegramSG.mrs",
      "type": "http",
      "format": "text",
      "interval": 86400
    },
    "TelegramUS": {
      ...ruleProviderCommon,
      "behavior": "classical",
      "url": "https://raw.githubusercontent.com/ccc52266/TelegramUS/main/clash",
      "path": "./rules/TelegramUS.mrs",
      "type": "http",
      "format": "text",
      "interval": 86400
    },
    "TelegramEU": {
      ...ruleProviderCommon,
      "behavior": "classical",
      "url": "https://raw.githubusercontent.com/ccc52266/TelegramEU/ccc52266-patch-1/clash",
      "path": "./rules/TelegramEU.mrs",
      "type": "http",
      "format": "text",
      "interval": 86400
    },
    "ADBLOCK": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://raw.githubusercontent.com/REIJI007/AdBlock_Rule_For_Clash/main/adblock_reject.mrs",
      "path": "./rules/ADBLOCK.mrs",
      "type": "http",
      "format": "mrs",
      "interval": 86400
    },
    "REJECT": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockmihomo.yaml",
      "path": "./rules/REJECT.mrs",
      "type": "http",
      "format": "yaml",
      "interval": 86400
    },
    "AWAvenue": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml",
      "path": "./rules/AWAvenue.mrs",
      "type": "http",
      "format": "yaml",
      "interval": 86400
    },
    "BANAD": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/banAd.yaml",
      "path": "./rules/BANAD.mrs",
      "type": "http",
      "format": "yaml",
      "interval": 86400
    },
    "KLEE": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://github.com/ccc52266/Klee/releases/download/v1.0/rules.mrs",
      "path": "./rules/KLEE.mrs",
      "type": "http",
      "format": "mrs",
      "interval": 86400
    },
    "Emby": {
      ...ruleProviderCommon,
      "behavior": "classical",
      "url": "https://raw.githubusercontent.com/ccc52266/Emby/main/clash",
      "path": "./rules/Emby.mrs",
      "type": "http",
      "format": "yaml",
      "interval": 86400
    },
    "YouTube": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs",
      "path": "./rules/YouTube.mrs",
      "type": "http",
      "format": "mrs",
      "interval": 86400
    },
    "OpenAI": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs",
      "path": "./rules/OpenAI.mrs",
      "type": "http",
      "format": "mrs",
      "interval": 86400
    },
    "TikTok": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs",
      "path": "./rules/TikTok.mrs",
      "type": "http",
      "format": "mrs",
      "interval": 86400
    },
    "Googleip": {
      ...ruleProviderCommon,
      "behavior": "ipcidr",
      "url": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs",
      "path": "./rules/Googleip.mrs",
      "type": "http",
      "format": "mrs",
      "interval": 86400
    },
    "Google": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs",
      "path": "./rules/Google.mrs",
      "type": "http",
      "format": "mrs",
      "interval": 86400
    },
    "Twitterip": {
      ...ruleProviderCommon,
      "behavior": "ipcidr",
      "url": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.mrs",
      "path": "./rules/Twitterip.mrs",
      "type": "http",
      "format": "mrs",
      "interval": 86400
    },
    "Twitter": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs",
      "path": "./rules/Twitter.mrs",
      "type": "http",
      "format": "mrs",
      "interval": 86400
    },
    "DouYin": {
      ...ruleProviderCommon,
      "behavior": "classical",
      "url": "https://raw.githubusercontent.com/ccc52266/douyin/main/README.md",
      "path": "./rules/DouYin.mrs",
      "type": "http",
      "format": "yaml",
      "interval": 86400
    },
    "BiliBili": {
      ...ruleProviderCommon,
      "behavior": "classical",
      "url": "https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/BiliBili/BiliBili_No_Resolve.yaml",
      "path": "./rules/BiliBili.mrs",
      "type": "http",
      "format": "yaml",
      "interval": 86400
    },
    "Pixiv": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.mrs",
      "path": "./rules/Pixiv.mrs",
      "type": "http",
      "format": "mrs",
      "interval": 86400
    },
    "Instagram": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/instagram.mrs",
      "path": "./rules/Instagram.mrs",
      "type": "http",
      "format": "mrs",
      "interval": 86400
    },
    "fakeip-filter": {
      ...ruleProviderCommon,
      "behavior": "domain",
      "url": "https://raw.githubusercontent.com/ccc52266/fakeip-filter/refs/heads/main/fake",
      "path": "./rules/fakeip-filter.mrs",
      "type": "http",
      "format": "yaml",
      "interval": 86400
    }
  };
    
  // 覆盖规则
  config["rules"] = [
    "RULE-SET,Game,Game",
    "RULE-SET,TelegramSG,TelegramSG",
    "RULE-SET,TelegramUS,TelegramUS",
    "RULE-SET,TelegramEU,TelegramEU",
    "RULE-SET,Emby,Emby",
    "RULE-SET,Pixiv,Pixiv",
    "RULE-SET,BiliBili,BiliBili",
    "AND,((PROCESS-NAME,com.dragon.read),(NOT,((OR,((DOMAIN-REGEX,v(26|3)-fq-tts\.fqnovelvod\.com),(DOMAIN-SUFFIX,fqnovelstatic.com),(DOMAIN-SUFFIX,fqnovel.com),(DOMAIN-SUFFIX,byteimg.com),(DOMAIN-SUFFIX,fqnovelpic.com)))))),BANAD",
    "RULE-SET,REJECT,BANAD",
    "RULE-SET,ADBLOCK,BANAD",
    "RULE-SET,AWAvenue,BANAD",
    "RULE-SET,BANAD,BANAD",
    "DOMAIN-REGEX,^ad.*com,BANAD",
    "GEOSITE,category-ads-all,BANAD",
    "DOMAIN-SUFFIX,mtalk.google.com,DIRECT",
    "DOMAIN,mtalk-staging.google.com,DIRECT",
    "DOMAIN,mtalk-dev.google.com,DIRECT",
    "DOMAIN,alt1-mtalk.google.com,DIRECT",
    "DOMAIN,alt2-mtalk.google.com,DIRECT",
    "DOMAIN,alt3-mtalk.google.com,DIRECT",
    "DOMAIN,alt4-mtalk.google.com,DIRECT",
    "DOMAIN,alt5-mtalk.google.com,DIRECT",
    "DOMAIN,alt6-mtalk.google.com,DIRECT",
    "DOMAIN,alt7-mtalk.google.com,DIRECT",
    "DOMAIN,alt8-mtalk.google.com,DIRECT",
    "RULE-SET,TikTok,TikTok",
    "RULE-SET,OpenAI,OpenAI",
    "RULE-SET,YouTube,YouTube",
    "RULE-SET,Instagram,Instagram",
    "RULE-SET,Twitter,Twitter",
    "RULE-SET,Twitterip,Twitter",
    "PROCESS-NAME,com.google.android.apps.googlevoice,GoogleVoice",
    "DOMAIN,lens.l.google.com,GoogleVoice",
    "DOMAIN,voice.googleapis.com,GoogleVoice",
    "DOMAIN-SUFFIX,services.googleapis.cn,Google",
    "DOMAIN-SUFFIX,xn--ngstr-lra8j.com,Google",
    "DOMAIN-SUFFIX,xn--ngstr-cn-8za9o.com,Google",
    "DOMAIN-SUFFIX,services.googleapis.cn,Google",
    "DOMAIN-SUFFIX,safebrowsing.googleapis.com,Google",
    "RULE-SET,Googleip,Google",
    "RULE-SET,Google,Google",
    "RULE-SET,DouYin,TikTok",
    "GEOSITE,microsoft,Final",
    "GEOSITE,cn,DIRECT",
    "GEOIP,cn,DIRECT",
    "RULE-SET,KLEE,BANAD",
    "MATCH,Final"
  ];
    
  // 返回修改后的配置
  return config;
}
